# alacritty.toml

[window]
# Set window dimensions (columns, lines)
dimensions = { columns = 100, lines = 30 }

# Start in maximized mode
startup_mode = "Maximized"

# Window padding (x, y)
padding = { x = 10, y = 10 }

# Whether the window should have borders and title bar
decorations = "Full"

[font]
# Normal (roman) font face
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

# Bold font face
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }

# Italic font face
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

# Font size in points
size = 16

[colors.primary]
background = "#f3ead3"
foreground = "#5c6a72"

[colors.normal]
black   = "#5c6a72"
red     = "#f85552"
green   = "#8da101"
yellow  = "#dfa000"
blue    = "#3a94c5"
magenta = "#df69ba"
cyan    = "#35a77c"
white   = "#d8d3ba"

[colors.bright]
black   = "#5c6a72"
red     = "#f85552"
green   = "#8da101"
yellow  = "#dfa000"
blue    = "#3a94c5"
magenta = "#df69ba"
cyan    = "#35a77c"
white   = "#d8d3ba"

[cursor]
style = { shape = "Block", blinking = "On" }

[scrolling]
history = 10000
multiplier = 3

[keyboard]
bindings = [
  # Example: Ctrl+Shift+T to spawn a new terminal window
  { key = "T", mods = "Control|Shift", action = "SpawnNewInstance" },

    # Option + Left → jump left by word
  { key = "Left",  mods = "Alt", chars = "\u001bb" },

  # Option + Right → jump right by word
  { key = "Right", mods = "Alt", chars = "\u001bf" },

  # Option + Backspace → delete previous word
  { key = "Back", mods = "Alt", chars = "\u0017" },

  # Option + Delete → delete next word (optional)
  { key = "Delete", mods = "Alt", chars = "\u001b[3;3~" }
]

